/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jose Antonio' at '9/12/16 9:18' with Gradle 3.2.1
 *
 * @author Jose Antonio, @date 9/12/16 9:18
 */
public class Library {
    public boolean someLibraryMethod() {
      for(int i=500;i<=1000;i+=2)
      {System.out.println(i);}
        return true;
    }
}
